name: Publish examples (presets)
on:
  schedule:
    - cron: "0 16 1/2 * *"
jobs:
  label:
    name: Label issue and pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
