name: Publish examples (presets)
on: push
jobs:
  label:
    name: Label issue and pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
